name: Hub Config Validation (R)

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'hub-config/**'
      - '!**README**'

jobs:
  validate-submission:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: hubverse-org/hubValidations, any::sessioninfo

      - name: Run validations
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          library("hubValidations")
          v <- hubValidations::check_config_hub_valid(
            hub_path = "${{ github.workspace }}"
          )
          hubValidations::check_for_errors(v, verbose = TRUE)
        shell: Rscript {0}
